# Generated by Django 5.2.5 on 2025-08-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_testimonial_rating_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')]),
        ),
    ]
