# Generated by Django 5.2.5 on 2025-08-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_shipment_price_shipment_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
